name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check for modified docfiles
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      docfiles: ${{ steps.filter.outputs.docfiles }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docfiles:
              - mkdocs.yml
              - "docs/**"
              - "**.md"

  build:
    needs: check
    if: ${{ needs.check.outputs.docfiles == 'true' }}
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Cache tox
        uses: actions/cache@v5
        with:
          path: .tox
          key: tox-${{ hashFiles('pyproject.toml') }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install tox
        run: python -m pip install tox

      - name: Build HTML documentation with tox
        run: tox run -e docs

      - name: Upload build artefact
        if: |
          ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) &&
          ((github.ref == 'refs/heads/main') || (github.ref_type == 'tag'))
        uses: actions/upload-pages-artifact@v4
        with:
          # path should be the -d, --site-dir target of the mkdocs build, that is run in
          # tox run -e docs
          path: site
          name: github-pages

  deploy:
    runs-on: ubuntu-latest
    name: (main only) Deploy to GH pages
    needs: build
    if: |
      ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) &&
      ((github.ref == 'refs/heads/main') || (github.ref_type == 'tag'))
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy from artifact
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
